[build]
target = "i586-pc-windows-msvc"

[target.i586-pc-windows-msvc]
rustflags = ["-C", "linker=lld-link", "-C", "link-args=/entry:entry /subsystem:native /base:0x7e00 /fixed /align:16 /nodefaultlib /stack:1 /heap:0"]
