name: Rust

# When to trigger the ci pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Gives us colour output for rust
env:
  CARGO_TERM_COLOR: always

# Array of jobs
jobs:
  # Job called BasicRustTest
  BasicRustTest:
    # Uses a ubuntu image
    runs-on: ubuntu-latest
    # The actions to take
    steps:
        # Set up rust enviroment
      - name: Install custom target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: i586-pc-windows-msvc
        # Fetch the git code to the image
      - name: Download the Repository
        uses: actions/checkout@v3
        # Run cargo unit tests
      - name: Cargo test all
        run: cargo test --jobs 2 --release --verbose 
        # Build PE-Parser which will build the bootloader
      - name: Cargo Build Release
        run: cargo r --release --verbose
        # Lint the code to ensure consistant formatting
      - name: Cargo Format Lint Check
        run: cargo fmt --all --check --verbose
        # Run the rust clippy pedantic warning check
      - name: Cargo Clippy Pedant
        run: cargo clippy
